# Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Only install deps first for better Docker caching
COPY package*.json ./
RUN npm install

# Copy all other files
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
